# Generated by Django 4.2.3 on 2023-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('limit_place', models.IntegerField()),
                ('booked_place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('limit_age', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('synopsis', models.TextField()),
                ('price', models.FloatField()),
                ('additionnal_price', models.BooleanField(default=False)),
                ('limit_place', models.IntegerField()),
                ('booked_place', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('limit_age', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('synopsis', models.TextField()),
                ('additionnal_price', models.BooleanField(default=False)),
                ('seance', models.ManyToManyField(to='cinema.seance')),
            ],
        ),
    ]
